name: studentsystem
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^1.1.0
  shared_preferences: ^2.4.0
  flutter_pdfview: ^1.4.0
  flutter_cached_pdfview: ^0.4.3
  permission_handler: ^11.3.1
  path: ^1.8.0
  external_path: ^2.0.1
  syncfusion_flutter_calendar: ^28.2.11
  

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  passwordfield: ^0.2.0
  signature: ^5.5.0

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.7

  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/documents/dummyPDF.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Poppins
  #      fonts:
  #      - asset: assets/fonts/Poppins-Regular.ttf
  #      - asset: assets/fonts/Poppins-Bold.ttf
  #        weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
